#!/usr/bin/env sh

# Symlink aware script paths and name
REAL_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$REAL_PATH")
SCRIPT_NAME=$(basename "$REAL_PATH")

# Config vars for `$SCRIPT_DIR/log.sh`
export LOG_NAMESPACE=" $SCRIPT_NAME"
# export LOG_LEVEL="${LOG_LEVEL:-info}"

# ╭───┤ Bootstrap & Argument parsing
# ╰─

_log() {
  "$SCRIPT_DIR/pu-log" "$@"
}

show_help() {
  man --pager cat "$SCRIPT_DIR/$SCRIPT_NAME.1"
}

# ╭───┤ Main. Start Here.
# ╰─

AVAILABLE_COMMANDS="log git-has-changed ensure-installed color"
COMMAND=$1
shift

if [ -z "$COMMAND" ]; then
  _log error -v available_commands "$AVAILABLE_COMMANDS" \
    "No command provided"
  exit 1
fi

if [ "$COMMAND" = "-h" ] || [ "$COMMAND" = "--help" ] || [ "$COMMAND" = "--hlep" ]; then
  show_help
  exit 0
fi

for cmd in $AVAILABLE_COMMANDS; do
  if [ "$cmd" = "$COMMAND" ]; then
    exec "$SCRIPT_DIR/pu-$COMMAND" "$@"
  fi
done

_log error -v command "$COMMAND" \
  -v available_commands "$AVAILABLE_COMMANDS" \
  "Unsupported command"

exit 1
