#!/usr/bin/env sh

# Symlink aware script paths and name
REAL_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$REAL_PATH")
SCRIPT_NAME=$(basename "$REAL_PATH")

# Config vars for `$SCRIPT_DIR/log.sh`
export LOG_NAMESPACE="󰏖 $SCRIPT_NAME"
export LOG_LEVEL="${LOG_LEVEL:-info}"

# ╭───┤ Bootstrap & Argument parsing
# ╰─

_color() {
  "$SCRIPT_DIR/pu-color" "$@"
}

_log() {
  "$SCRIPT_DIR/pu-log" "$@"
}

_tadaa() {
  "$SCRIPT_DIR/pu-tadaa" "$@"
}

show_help() {
  cat <<EOF
$(_color gray "USAGE:")
  $SCRIPT_NAME [OPTIONS] <package1> [package2] [...]

$(_color gray "OPTIONS:")
  -f, --force                       Reinstall existing packages
  -pm, --package-manager <manager>  Specify package manager to use
  -h, --help                        Show detailed man page
  --                                Pass remaining arguments as flags to package manager

$(_color gray "SUPPORTED PACKAGE MANAGERS:")
  pacman, apt, yum, dnf, brew, npm
EOF
}

PACKAGE_MANAGER=""
PACKAGE_MANAGER_FLAGS=""
PACKAGES=""
SUPPORTED_PACKAGE_MANAGERS="pacman apt yum dnf brew npm"
FORCE_REINSTALL=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    -f | --force)
      FORCE_REINSTALL="true"
      shift
      ;;
    -pm | --package-manager)
      PACKAGE_MANAGER="$2"
      shift 2
      ;;
    -h | --help | --hlep)
      show_help
      exit 0
      ;;
    --)
      shift
      PACKAGE_MANAGER_FLAGS="$*"
      break
      ;;
    -?*)
      _log error -v name "$1" "Unknown flag."
      show_help
      exit 1
      ;;
    *)
      [ -z "$PACKAGES" ] && PACKAGES="$1" || PACKAGES="$PACKAGES $1"
      shift
      ;;
  esac
done

# ╭───┤ Domain Functions
# ╰─

detect_os_pkg_manager() {
  if command -v pacman >/dev/null 2>&1; then
    echo "pacman"
  elif command -v apt >/dev/null 2>&1; then
    echo "apt"
  elif command -v yum >/dev/null 2>&1; then
    echo "yum"
  elif command -v dnf >/dev/null 2>&1; then
    echo "dnf"
  elif command -v brew >/dev/null 2>&1; then
    echo "brew"
  fi
}

ensure_installed() {
  install_cmd_args="$PACKAGE_MANAGER_FLAGS"
  install_cmd=""

  case "$PACKAGE_MANAGER" in
    pacman)
      install_cmd_args="$install_cmd_args --sync --noconfirm"
      [ -z "$FORCE_REINSTALL" ] && install_cmd_args="$install_cmd_args --needed"
      install_cmd="sudo pacman $install_cmd_args $PACKAGES"
      ;;
    apt)
      export DEBIAN_FRONTEND=noninteractive
      install_cmd_args="$install_cmd_args --yes"
      [ -n "$FORCE_REINSTALL" ] && install_cmd_args="$install_cmd_args --reinstall"
      install_cmd="sudo apt update --quiet && sudo apt install $install_cmd_args $PACKAGES"
      ;;
    yum | dnf)
      install_cmd_args="$install_cmd_args --assumeyes"
      [ -n "$FORCE_REINSTALL" ] && install_cmd_args="$install_cmd_args --reinstall"
      install_cmd="sudo $PACKAGE_MANAGER install $install_cmd_args $PACKAGES"
      ;;
    brew)
      [ -n "$FORCE_REINSTALL" ] && install_cmd_args="$install_cmd_args --force"
      install_cmd="brew install $install_cmd_args $PACKAGES"
      ;;
    npm)
      install_cmd_args="$install_cmd_args --global"
      [ -n "$FORCE_REINSTALL" ] && install_cmd_args="$install_cmd_args --force"
      install_cmd="npm install $install_cmd_args $PACKAGES"
      ;;
  esac

  _log info \
    -v pm "$PACKAGE_MANAGER" \
    -v pm_user_flags "$PACKAGE_MANAGER_FLAGS" \
    -v command "$install_cmd" \
    "Running command…"

  # shellcheck disable=SC2086 # Intentional word splitting for packages and flags
  $install_cmd
}

is_package_manager_supported() {
  case "$SUPPORTED_PACKAGE_MANAGERS" in
    *"$1"*) return 0 ;;
    *) return 1 ;;
  esac
}

# ╭───┤ Main. Start Here.
# ╰─

if [ -z "$PACKAGES" ]; then
  _log error "No package provided"
  show_help
  exit 1
fi

if [ -z "$PACKAGE_MANAGER" ]; then
  PACKAGE_MANAGER="$(detect_os_pkg_manager)"
  _log info \
    -v pm "$PACKAGE_MANAGER" \
    -v os "$(uname -s -r)" \
    "Auto-detected package manager"
fi

if [ -n "$PACKAGE_MANAGER" ] && ! is_package_manager_supported "$PACKAGE_MANAGER"; then
  _log error -v name "$PACKAGE_MANAGER" \
    "Unsupported package manager"
  show_help
  exit 1
fi

if ! command -v "$PACKAGE_MANAGER" >/dev/null 2>&1; then
  _log error -v name "$PACKAGE_MANAGER" \
    "Package manager not installed"
  exit 1
fi

for package_name in $PACKAGES; do
  if ! echo "$package_name" | grep -qE '^[a-zA-Z0-9._+-]+$'; then
    _log error -v package "$package_name" \
      "Invalid package name. Only alphanumeric characters, dots, underscores, hyphens and plus signs are allowed"
    exit 1
  fi
done

ensure_installed
